WITH 
CONTRATOSACTIVOS AS(
    SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD),10) AS ACT_ACCT_CD, FECHA_EXTRACCION
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY ACT_ACCT_CD, FECHA_EXTRACCION
)
, PARQUEEMPAQUETADO AS(
SELECT RIGHT(CONCAT('0000000000',Contrato),10) AS Contrato
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_PARQUE_EMPAQUETADO_2021_T`
GROUP BY Contrato
)

SELECT DATE_TRUNC(FECHA_EXTRACCION, MONTH) AS MES, COUNT(DISTINCT ACT_ACCT_CD) AS NumActivosCRM
 ,COUNT(DISTINCT Contrato) AS NumCruce, ROUND(COUNT(DISTINCT Contrato)/COUNT(DISTINCT ACT_ACCT_CD),2) AS PorcCruce
FROM CONTRATOSACTIVOS a LEFT JOIN  PARQUEEMPAQUETADO p ON a.ACT_ACCT_CD=p.Contrato
GROUP BY MES
ORDER BY MES ASC
