WITH 
CONTRATOSCRM AS(
    SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD),10) AS ACT_ACCT_CD, FECHA_EXTRACCION,
    PD_BB_PROD_NM, PD_TV_PROD_CD, PD_VO_PROD_NM
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-16_FINAL_HISTORIC_CRM_FILE_2021_D`
    GROUP BY 1,2,3,4,5
)
, PARQUEEMPAQUETADO AS(
SELECT RIGHT(CONCAT('0000000000',Contrato),10) AS Contrato, Clasificacion
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-01-13_CR_PARQUE_EMPAQUETADO_2021_T`
GROUP BY 1,2
)
SELECT DISTINCT Contrato, FECHA_EXTRACCION, PD_BB_PROD_NM, PD_TV_PROD_CD, PD_VO_PROD_NM, Clasificacion
FROM CONTRATOSCRM c INNER JOIN PARQUEEMPAQUETADO p ON c.ACT_ACCT_CD=p.Contrato
ORDER BY Contrato, FECHA_EXTRACCION
